apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service-dev
  namespace: argocd
  labels:
    app: product-service
    env: dev
spec:
  project: default
  source:
    repoURL: https://github.com/team4-coding-gamja/UNBOX-INFRA.git
    targetRevision: feat/ArgoCD-dev
    path: gitops/charts
    helm:
      valueFiles:
        - values.yaml
        - ../apps/product/values.yaml
        - ../apps/product/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: unbox-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
