apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config-dev
  namespace: argocd
  labels:
    app: external-secrets-config
    env: dev
spec:
  project: default
  source:
    repoURL: https://github.com/team4-coding-gamja/UNBOX-INFRA.git
    targetRevision: feat/ArgoCD-dev
    path: gitops/infra/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: unbox-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
