apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trade-service-dev-synasync
  namespace: argocd
  labels:
    app: trade-service
    env: dev-synasync
spec:
  project: default
  source:
    repoURL: https://github.com/team4-coding-gamja/UNBOX-INFRA.git
    targetRevision: feat/ArgoCD-dev-synasync
    path: gitops/charts
    helm:
      valueFiles:
        - values.yaml
        - ../apps/trade/values.yaml
        - ../apps/trade/values-dev-synasync.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: unbox-app-synasync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
