apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service-dev
  namespace: argocd
  labels:
    app: order-service
    env: dev
spec:
  project: default
  source:
    repoURL: https://github.com/team4-coding-gamja/UNBOX-INFRA.git
    targetRevision: feat/ArgoCD-dev
    path: gitops/charts
    plugin:
      name: parameter-store-injector-v1.0
      env:
        - name: SERVICE_NAME
          value: order
        - name: VALUES_FILES
          value: "values.yaml,../apps/order/values.yaml,../apps/order/values-dev.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: unbox-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
