apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-gateway-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/team4-coding-gamja/UNBOX-INFRA.git # Update if needed, assuming user knows repo
    targetRevision: HEAD
    path: gitops/infra/ingress-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: unbox-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
