# 기본적으로 Linkerd는 끔 (필요하면 켬)
linkerd:
  enabled: false

# 기본 이미지 설정 (각 서비스별로 오버라이드)
image:
  repository: ""
  tag: "latest"
  pullPolicy: "Always"

# 기본 서비스 설정
service:
  port: 80
  targetPort: 8080

containerPort: 8080
replicaCount: 1

# 기본 리소스 (작게)
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"

# Ingress 설정
ingress:
  enabled: false
  path: "/"
  groupName: "unbox-dev"
  certificateArn: "arn:aws:acm:ap-northeast-2:632941626317:certificate/23cdae56-b916-4d5e-8877-d0c50f93312f"  # ACM Certificate ARN (Parameter Store: /unbox/dev/acm/certificate_arn)
  securityGroup: "unbox-dev-alb-sg"

# 환경변수 리스트 (각 서비스별 values 파일에서 오버라이드)
env: {}
  