apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit-dev
  namespace: argocd
  labels:
    component: monitoring
    env: dev
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.47.7
    helm:
      releaseName: fluent-bit
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
