apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-dev
  namespace: argocd
  labels:
    component: monitoring
    env: dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.10.3
      helm:
        releaseName: tempo
        valueFiles:
          - $values/gitops/infra/monitoring/tempo/values.yaml
    - repoURL: https://github.com/team4-coding-gamja/UNBOX-INFRA.git
      targetRevision: feat/ArgoCD-dev
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
